---
#Please see variablehelp.md if you are confused

username: "<your username at setup>"

puid: "<id>"

pgid: "<id>"

ip_address: "<your server IP address>"

timezone: "<your timezone>"

domain: "<your domain name>"

cloudflare_email: "<your cloudflare email>"

cloudflare_api_key: "<your global cloudflare api key>"

traefik_basic_auth_hash: "<traefik hashed username and pass>"

jwt_secret: "<athelia jwt secret>"

authelia_sqlite_encryption_key: "<authelia encryption key>"

google_mail: "<google email>"

google_insecure_app_pass: "<app password for google account>"

authelia_admin_mail: "<email for authelia>"

authelia_admin_argon2id_pass: "<authelia argon2 password>"

vaultwarden_admin_argon2id_pass: "<vaultwarden admin page argon2 password>"

wg_password: "<wireguard vpn password>"

codeserver_password: "<code server password>"

pihole_password: "<pihole password>"

mysql_password: "<mysql password>"

vpn_provider: "<your vpn provider>"

vpn_config: "<location of vpn server>"

vpn_username: "<vpn provider username>"

vpn_password: "<vpn provider password>"

local_network: "<your local network>"

shell: /usr/bin/fish

docker_dir: /home/{{ username }}/docker

data_dir: /home/{{ username }}/data

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip
  - fish
  - speedtest-cli
  - htop
  - exa
  - git
  - neofetch
  - neovim
  - tmux
  - expect

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

#
# SSH (geerlingguy.security)
#
security_ssh_port: 69 #ssh listening port (default 22)
security_sudoers_passwordless: ["{{ username }}"]
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "23:00"
security_autoupdate_mail_on_error: false
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
